<?php
/**
 * @var \Learning\HelloWorld\Block\Display $block
 */
?>
<a href="<?= $block->getView() ?>">view list data</a>
<h3 style="text-align: center;">EDIT DATA</h3>
<form action="<?= $block->getFormEdit() ?>" method="post">
    <label for="name">Name:</label>
    <input type="text" name="name" value="<?= $block->getSuaData()->getName() ?>" required>
    <label for="title">Title:</label>
    <input type="text" name="title" value="<?= $block->getSuaData()->getTitle() ?>" required>
    <input type="submit" value="Edit Data">
</form>
